---
os: linux
dist: trusty
sudo: required
# https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
# for the new trusty image.
group: edge

env:
  global:
    - GOROOT=/usr/local/git/go
    - GOPATH=/usr/local/git/golib
  matrix:
    # This is the chrooted archlinux environemnt to check provision.yml.
    # https://github.com/mikkeloscar/arch-travis/blob/master/README.md
    - ARCH_TRAVIS_ARCH=x86_64 ARCH_TRAVIS_CLEAN_CHROOT=1 ARCH_TRAVIS_CONFIRM_YES=1
    # This is the ubuntu environment, to check guest.yml.
    - ARCH_TRAVIS_GUEST_ENV=1

language: c

compiler:
  - gcc

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - openssh
    - python2
    - python2-pip
    #- procps-ng
    #- reflector
    # aur
    #- screenfetch-git
  script:
    # script run under chrooted environment
    #- "sudo screenfetch"
    #- "reflector --verbose -l 20 --sort rate -p https"
    - "sudo -E make test"

script:
  - if [[ "${ARCH_TRAVIS_CLEAN_CHROOT}" == "1" ]]; then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash; fi
  - if [[ "${ARCH_TRAVIS_GUEST_ENV}" == "1" ]]; then sudo -E make test-guest; fi
