---
# https://github.com/mikkeloscar/arch-travis/blob/master/README.md
# http://blog.fossasia.org/arch-linux-for-travis-ci/
sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1
  - ARCH_TRAVIS_CONFIRM_YES=1

language: c

compiler:
  - gcc
  - clang

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - procps-ng
    - reflector
    # aur
    - screenfetch-git
    # pacman packages
    - ansible
    - openssh
  script:
    # script run under chroot environment
    - "sudo screenfetch"
    - "reflector --verbose -l 20 --sort rate -p https"
    - "echo $CC"
    - "touch test_file"
    - "systemctl status sshd"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - "ls -l"
