---
# https://github.com/mikkeloscar/arch-travis/blob/master/README.md
sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1
  - ARCH_TRAVIS_CONFIRM_YES=1

language: c

compiler:
  - gcc
  - clang

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - ansible
    - openssh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - "systemctl start sshd"
  - "systemctl status sshd"
  - "ls -l"
