---
# https://github.com/mikkeloscar/arch-travis/blob/master/README.md
# http://blog.fossasia.org/arch-linux-for-travis-ci/
sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1
  - ARCH_TRAVIS_CONFIRM_YES=1

language: c

compiler:
  - gcc
  - clang

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - openssh
    - ansible
    - procps-ng
    - reflector
    # aur
    - screenfetch-git
  script:
    # script run under chroot environment
    - "uname -an"
    - "sudo screenfetch"
    - "reflector --verbose -l 20 --sort rate -p https"
    - "echo $CC"
    # There is an issue on the libvirt in the chroot environment.
    - "ansible -m ping -i inventory.travis -c local host"

script:
  # script run under the host environment.
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
