---
# https://github.com/mikkeloscar/arch-travis/blob/master/README.md
sudo: required

arch:
  repos:
    - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    # pacman packages
    - ansible
    - openssh

script:
  - "systemctl start sshd"
  - "systemctl status sshd"
  - "ls -l"
