---
# https://github.com/mikkeloscar/arch-travis/blob/master/README.md
sudo: required

arch:
  repos:
    - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    # pacman packages
    - libsystemd
    - systemd
    - ansible
    - openssh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - "systemctl start sshd"
  - "systemctl status sshd"
  - "ls -l"
