---
- name: arch-on-air game playbook
  hosts: arch
  vars:
    ci: false
    latest: false
  gather_facts: false
  tasks:
    - name: install ruby and libraries for games
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - ruby
        - mpg123
        - sdl2_ttf
      become: true

    - name: install ruby gems
      gem: name={{ item }} state=present
      with_items:
        - gosu
        - chipmunk
      become: true
