---
- name: setup ubuntu guest
  hosts: guests
  vars:
    verbose: false
  gather_facts: false
  tasks:
    - name: add user to the src group
      user:
        name: "{{ ansible_user }}"
        group: adm
        groups: src,sudo
        append: yes
      become: true

    - name: create /usr/local/git directory
      file: path=/usr/local/git state=directory group=src mode=0775
      become: true

    - name: build & install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
