---
- name: archlinux based guest
  hosts: guest
  gather_facts: false
  vars:
    ci: false
  tasks:
    - name: update hostname to be in sync with the inventory host name
      hostname: name={{ inventory_hostname_short }}
      become: true
      when: not ci|bool

    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - hosts
        - systemd/network/ens3.network
        - systemd/network/ens4.network
        - systemd/network/ens5.network
      become: true
      when: not ci|bool

    - name: drop bond0 to avoid the systemd-networkd crash
      file:
        path: "/etc/{{ item }}"
        state: absent
      with_items:
        - systemd/network/bond0.netdev
        - systemd/network/bond0.network
      become: true
      when: not ci|bool

    - name: restart systemd services
      systemd: name={{ item }} enabled=true state=restarted
      with_items:
        - systemd-networkd
        - systemd-resolved
        - systemd-timesyncd
      become: true
      when: not ci|bool

    - name: create git and src directories for having fun
      file: path={{ lookup('env', 'HOME') }}/{{ item }} state=directory mode=0700
      with_items:
        - git
        - src
