---
- name: setup ubuntu guest
  hosts: guest
  vars:
    rabbit: true
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go-1.6
  gather_facts: true
  tasks:
    - name: update /etc/network/interfaces
      template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
        mode: 0644
        owner: root
        group: root
      become: true

    - name: install console apps
      apt: name={{ item }} state=present update_cache=true
      items:
        - vim
        - tmux
        - tree
        - jq
        - aspell
        - aspell-en
        - cowsay
      become: true

    - name: install network tools
      apt: name={{ item }} state=present update_cache=false
      items:
        - w3m
        - curl
        - tcpdump
        - traceroute
      become: true

    - name: install developer tools
      apt: name={{ item }} state=present update_cache=false
      items:
        - binutils
        - g++
        - git
        - gdb
        - make
        - cscope
        - autoconf
        - automake
        - libtool
        - bzip2
        - unzip
        - golang-1.6
        - cpanminus
        - python-all
        - python-pip
        - python-six
        - python3-pip
        - python3-setuptools
        - graphviz
        - debhelper
        - dh-autoreconf
        - libmysqlclient-dev
        - libssl-dev
        - openssl
        - procps
        - libvirt-dev
        - libvirt-bin
        - libcap-ng-dev
        - vagrant
        - virtualbox
        - chef-zero
      become: true

    - name: install developer tools for ubuntu16.04 or above
      apt: name={{ item }} state=present update_cache=false
      items:
        - cgroup-tools
        - chefdk
        - vagrant
        - virtualbox
      become: true
      when: ansible_distribution_version == "16.04"

    - name: install docker daemon and cli
      import_tasks: tasks/docker-ubuntu-1604.yml
      when: ansible_distribution_version == "16.04"

    - name: setup RabbitMQ environment
      import_tasks: tasks/rabbit.yml
      vars:
        scheme: amqp
        username: rabbit
        password: RabbitMQ
        cluster: "localhost:5672"
        vhost: hole
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
      when: rabbit|bool and not travis_ci|bool

    - name: light the fire!
      import_tasks: tasks/all.yml
