---
- name: setup ubuntu guest
  hosts: guest
  vars:
    kvm: true
    rabbit: true
    latest: false
    verbose: true
  gather_facts: false
  tasks:
    - name: add user to the src group
      user:
        name: "{{ ansible_user }}"
        group: adm
        groups: src,sudo
        append: true
      become: true

    - name: create /usr/local/git directory
      file: path=/usr/local/git state=directory group=src mode=0775
      become: true

    - name: install general pre-requisite packages
      apt: name={{ item }} state=present update_cache=true
      items:
        - binutils
      become: true

    - name: build & install the latest golang
      import_tasks: tasks/golang.yml
      when: latest|bool

    - name: build & install the latest terraform
      import_tasks: tasks/terraform.yml
      when: latest|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: latest|bool

    - name: install the latest perl
      import_tasks: tasks/perl.yml
      when: latest|bool

    - name: setup KVM environment
      import_tasks: tasks/kvm.yml
      when: kvm|bool

    - name: setup RabbitMQ environment
      import_tasks: tasks/rabbit.yml
      vars:
        scheme: amqp
        username: rabbit
        password: RabbitMQ
        cluster: "localhost:5672"
        vhost: hole
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
      when: rabbit|bool
