---
- name: setup ubuntu guest
  hosts: guests
  vars:
    verbose: false
  gather_facts: false
  tasks:
    - name: install packages
      apt: name={{ item }} state=present update_cache=yes
      items:
        - golang-1.6
        - w3m
        - python
        - python-pip
        - libssl-dev
      become: true

    - name: add user to the src group
      user:
        name: "{{ ansible_user }}"
        group: adm
        groups: src,sudo
        append: yes
      become: true

    - name: create /usr/local/git directory
      file: path=/usr/local/git state=directory group=src mode=0775
      become: true

    - name: clone git repos
      git:
        repo: "{{ item.repo }}"
        dest: "/usr/local/git/{{ item.dest }}"
        update: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      with_items:
        - { repo: "git@github.com:golang/go", dest: go }
        - { repo: "git@github.com:ansible/ansible", dest: ansible }
      register: result

    - name: print the result
      debug: var=result
      when: verbose|bool

    - name: build & install the latest golang
      shell: GOROOT_BOOTSTRAP=/usr/lib/go-1.6 ./make.bash
      args:
        chdir: /usr/local/git/go/src
      register: result

    - name: print the result
      debug: var=result
      when: verbose|bool

    - name: install the latest ansible
      include_tasks: tasks/ansible.yml
