---
- name: setup ubuntu guest
  hosts: guest
  vars:
    rabbit: true
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go-1.6
  gather_facts: true
  tasks:
    - name: install console apps
      apt: name={{ item }} state=present update_cache=true
      items:
        - vim
        - tmux
        - tree
        - jq
        - aspell
        - aspell-en
      become: true

    - name: install network tools
      apt: name={{ item }} state=present update_cache=false
      items:
        - w3m
        - curl
        - tcpdump
        - traceroute
      become: true

    - name: install developer tools
      apt: name={{ item }} state=present update_cache=false
      items:
        - binutils
        - g++
        - git
        - gdb
        - make
        - cscope
        - autoconf
        - automake
        - libtool
        - bzip2
        - unzip
        - golang-1.6
        - cpanminus
        - python
        - python-pip
        - python-six
        - graphviz
        - debhelper
        - dh-autoreconf
        - libssl-dev
        - openssl
        - procps
        - libvirt-dev
        - libvirt-bin
      become: true

    - name: install docker daemon and cli
      import_tasks: tasks/docker-ubuntu-1604.yml
      when: ansible_distribution_version == "16.04"

    - name: setup RabbitMQ environment
      import_tasks: tasks/rabbit.yml
      vars:
        scheme: amqp
        username: rabbit
        password: RabbitMQ
        cluster: "localhost:5672"
        vhost: hole
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
      when: rabbit|bool and not travis_ci|bool

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: configure the docker environment
      import_tasks: tasks/docker.yml
      when: not travis_ci|bool

    - name: install the latest Open vSwitch
      import_tasks: tasks/openvswitch.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yml
      when: latest|bool and not travis_ci|bool

    - name: install the latest etcd
      import_tasks: tasks/etcd.yml
      when: latest|bool

    - name: install the latest kubernetes
      import_tasks: tasks/kubernetes.yml
      when: latest|bool and not travis_ci|bool

    - name: install the latest terraform
      import_tasks: tasks/terraform.yml
      when: latest|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: latest|bool

    - name: install the latest perl
      import_tasks: tasks/perl.yml
      when: latest|bool
