---
- name: setup ubuntu guest
  hosts: guests
  vars:
    golang: true
    terraform: true
    ansible: true
    perl: true
    verbose: true
  gather_facts: false
  tasks:
    - name: add user to the src group
      user:
        name: "{{ ansible_user }}"
        group: adm
        groups: src,sudo
        append: yes
      become: true

    - name: create /usr/local/git directory
      file: path=/usr/local/git state=directory group=src mode=0775
      become: true

    - name: install general pre-requisite packages
      apt: name={{ item }} state=present update_cache=yes
      items:
        - libvirt-dev
      become: true

    - name: build & install the latest golang
      import_tasks: tasks/golang.yml
      when: golang|bool

    - name: build & install the latest terraform
      import_tasks: tasks/terraform.yml
      when: terraform|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: ansible|bool

    - name: install the latest perl
      import_tasks: tasks/perl.yml
      when: perl|bool
