---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    ci: false
    full: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: additional developer tools
      pacman:
        state: present
        update_cache: false
        name:
          - binutils
          - gettext
          - bison
          - flex
          - clang
          - llvm
          - lldb
          - bpf
          - valgrind
          - dtc
          - patch
          - m4
          - autoconf
          - automake
          - pkgconf
          - libtool
          - yarn
          - cpanminus
          - python-pip
          - cscope
          - yasm
          - clisp
          - wabt
          - cmake
          - gtest
          - numactl
          - fakeroot
          - unzip
          - jq
          - flatbuffers
          - postgresql-libs
          - mariadb-clients
          - jdk-openjdk
          - maven
      become: true

    # https://wiki.archlinux.org/index.php/improving_performance
    - name: install perf tools!
      pacman:
        state: present
        update_cache: false
        name:
          - time
          - perf
          - iputils
          - netperf
          - iperf3
          - stress
          - sysstat
          - sysbench
          - sysdig
          - fio
          - iotop
      become: true

    # https://rust-embedded.github.io/book/intro/install/linux.html
    - name: cross compile environment
      pacman:
        state: present
        update_cache: false
        name:
          - arm-none-eabi-gdb
          - qemu-headless-arch-extra
          - openocd
      become: true

    - name: install local RabbitMQ message broker
      import_tasks: tasks/rabbit.yaml
      vars:
        scheme: amqp
        username: rabbit
        password: RabbitMQ
        cluster: "127.0.0.1:5672"
        vhost: mx
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
      when: full|bool and not ci|bool

    - name: create git and src directories for having fun
      file: path={{ lookup('env', 'HOME') }}/{{ item }} state=directory mode=0700
      with_items:
        - git
        - src

    - name: install the latest perl packages
      import_tasks: tasks/perl.yaml

    - name: install the latest python packages
      import_tasks: tasks/python.yaml

    - name: install the latest golang
      import_tasks: tasks/golang.yaml

    - name: install golang tools
      import_tasks: tasks/gopkg.yaml

    - name: install the latest asciinema
      import_tasks: tasks/asciinema.yaml

    - name: python2 for gcloud...
      pacman:
        state: present
        update_cache: false
        name:
          - python2
      become: true

    - name: install the latest gcloud
      import_tasks: tasks/gcloud.yaml

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yaml
      when: not ci|bool

    - name: install ftrace, kernel tracer
      import_tasks: tasks/ftrace.yaml
      when: full|bool

    - name: install bcc for BPF fun
      import_tasks: tasks/bcc.yaml

    - name: install bpftrace to trace anything
      import_tasks: tasks/bpftrace.yaml
      when: full|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yaml
      when: full|bool

    # https://github.com/rust-lang/rust#building-on-nix
    - name: install the latest rust
      import_tasks: tasks/rust.yaml
      when: full|bool

    - name: install the latest terraform
      import_tasks: tasks/terraform.yaml
      when: full|bool
