---
- name: arch-on-air hack playbook
  hosts: host
  connection: local
  vars:
    latest: false
    # Until ansible pacman module in 2.5 has been fixed...
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - gcc-fortran
        - cpanminus
        - libmariadbclient
        - jre8-openjdk-headless
      become: true

    - name: install perf tools!
      pacman: name={{ item }} state=present update_cache=false
      with_items:
        - stress
        - sysstat
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: light the fire!
      import_tasks: tasks/all.yml
