---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install perf tools!
      pacman: name={{ item }} state=present update_cache=false
      with_items:
        - time
        - iperf3
        - stress
        - sysstat
      become: true

    - name: install kvm/container to create virtual environment
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - qemu-headless
        - libvirt
        - libvirt-python
        - virt-install
        - virt-viewer
        - tigervnc
        - docker
        - python-lxml
        - python2-docker
        - python2-requests
      become: true

    - name: add user to the libvirt/container groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: libvirt,docker
      become: true
      when: not travis_ci|bool

    - name: install the latest perl packages
      import_tasks: tasks/perl.yml

    - name: install the latest python packages
      import_tasks: tasks/python.yml

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml

    - name: install the latest asciinema
      import_tasks: tasks/asciinema.yml

    - name: install the latest Open vSwitch
      import_tasks: tasks/openvswitch.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the latest terraform
      import_tasks: tasks/terraform.yml

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yml
      when: not travis_ci|bool
