---
- name: arch-on-air hack playbook
  hosts: host
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - bc
        - gcc
        - gcc-fortran
        - git
        - gdb
        - m4
        - make
        - autoconf
        - automake
        - libtool
        - pkg-config
        - unzip
        - go
        - cscope
        - cpanminus
        - python-setuptools
        - python2
        - python2-pip
        - python2-six
        - qemu-headless
        - libvirt
        - libvirt-python2
        - docker
        - docker-machine
        - libmariadbclient
        - jre8-openjdk-headless
      become: true

    - name: add user to the developer groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: libvirt,docker
      become: true
      when: not travis_ci|bool

    - name: light the fire!
      import_tasks: tasks/all.yml
