---
- name: arch-on-air hack playbook
  hosts: host
  connection: local
  vars:
    latest: false
    # Until ansible pacman module in 2.5 has been fixed...
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - gcc-fortran
        - cpanminus
        - libmariadbclient
        - jre8-openjdk-headless
      become: true

    - name: install perf tools!
      pacman: name={{ item }} state=present update_cache=false
      with_items:
        - stress
        - sysstat
      become: true

    - name: install kvm/docker tools for virtualization environment
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - qemu-headless
        - libvirt
        - libvirt-python
        - virt-install
        - virt-viewer
        - tigervnc
        - docker
        - docker-machine
      become: true

    - name: add user to the developer groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: uucp,libvirt,docker
      become: true
      when: not travis_ci|bool

    - name: setup libvirt group
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: 'unix_sock_group'
        line: 'unix_sock_group = "libvirt"'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: setup qemu group
      lineinfile:
        path: /etc/libvirt/qemu.conf
        regexp: 'group = '
        line: 'group = "kvm"'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: let's suckless!
      import_tasks: tasks/suckless.yml

    - name: light the fire!
      import_tasks: tasks/all.yml
