---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: additional developer tools
      pacman:
        state: present
        update_cache: false
        name:
          - linux-headers
          - yasm
          - binutils
          - bc
          - bison
          - flex
          - cpio
          - clang
          - llvm
          - gdb
          - valgrind
          - dtc
          - go
          - clisp
          - wabt
          - patch
          - m4
          - autoconf
          - automake
          - libtool
          - pkg-config
          - cmake
          - numactl
          - fakeroot
          - unzip
          - nodejs
          - yarn
          - jq
          - asciidoc
          - mariadb-clients
      become: true

    # https://wiki.archlinux.org/index.php/improving_performance
    - name: install perf tools!
      pacman:
        state: present
        update_cache: false
        name:
          - time
          - perf
          - netperf
          - iperf3
          - stress
          - sysstat
      become: true

    - name: install ftrace, kernel tracer
      import_tasks: tasks/ftrace.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml
