---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: additional developer tools
      pacman:
        state: present
        update_cache: false
        name:
          - linux-headers
          - yasm
          - binutils
          - bc
          - bison
          - flex
          - cpio
          - clang
          - llvm
          - gdb
          - valgrind
          - docker
          - dtc
          - go
          - clisp
          - wabt
          - patch
          - m4
          - autoconf
          - automake
          - pkgconf
          - libtool
          - cmake
          - gtest
          - numactl
          - fakeroot
          - unzip
          - nodejs
          - yarn
          - jq
          - asciidoc
          - mariadb-clients
      become: true

    # https://wiki.archlinux.org/index.php/improving_performance
    - name: install perf tools!
      pacman:
        state: present
        update_cache: false
        name:
          - time
          - perf
          - strace
          - netperf
          - iperf3
          - stress
          - sysstat
          - sysbench
      become: true

    - name: add user to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: docker
      become: true

    - name: enable basic services
      systemd: name={{ item }} enabled=true
      with_items:
        - docker
      become: true
      when: not travis_ci|bool

    # https://github.com/rust-lang/rust#building-on-nix
    - name: install the latest rust
      import_tasks: tasks/rust.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install ftrace, kernel tracer
      import_tasks: tasks/ftrace.yml

    - name: install bcc for BPF fun
      import_tasks: tasks/bcc.yml

    - name: install bpftrace to trace anything
      import_tasks: tasks/bpftrace.yml
