---
- name: arch-on-air hack playbook
  hosts: host
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: false
  tasks:
    - name: add user to the developer groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: libvirt,docker
      become: true
      when: not travis_ci|bool

    - name: light the fire!
      import_tasks: tasks/all.yml
