---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    latest: false
    # Until ansible pacman module in 2.5 has been fixed...
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - gcc-fortran
        - jre8-openjdk-headless
      become: true

    - name: install perf tools!
      pacman: name={{ item }} state=present update_cache=false
      with_items:
        - stress
        - sysstat
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: install the latest perl packages
      import_tasks: tasks/perl.yml

    - name: install the latest python packages
      import_tasks: tasks/python.yml

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml

    - name: install the latest asciinema
      import_tasks: tasks/asciinema.yml

    - name: install the latest Open vSwitch
      import_tasks: tasks/openvswitch.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the OpenTracing
      import_tasks: tasks/tracing.yml

    - name: install the latest terraform
      import_tasks: tasks/terraform.yml
      when: not travis_ci|bool

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yml
      when: latest|bool and not travis_ci|bool
