---
- name: arch-on-air hypvervisor playbook
  hosts: host
  gather_facts: true
  vars:
    ci: false
    latest: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
    guest_emulator: /usr/bin/qemu-system-x86_64
    guest_arch: x86_64
    guest_machine: pc-i440fx-2.11
    guest_disk_type: block
    guest_disk_path: /dev/images
    guest_disk_source_type: dev
    guest_intf0_dev_prefix: ens3-
    guest_intf1_dev_prefix: ens4-
    guest_intf2_dev_prefix: ens5-
    guests:
      - { id: '01', type: arch }
      - { id: '02', type: arch }
      - { id: '03', type: arch }
      - { id: '04', type: arch }
      - { id: '05', type: arch }
      - { id: '06', type: arch }
      - { id: '07', type: arch }
      - { id: '08', type: arch }
      - { id: '09', type: arch }
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
  tasks:
    - name: install kvm/container for the virtual environment
      pacman:
        state: present
        force: true
        update_cache: false
        name:
          - qemu-headless
          - libvirt
          - libvirt-python
          - virt-install
          - virt-viewer
          - tigervnc
          - python
          - python-pip
          - python-lxml
          - python-virtualenv
      become: true

    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - hosts
        - modprobe.d/modprobe.conf
        - systemd/network/br0.network
      become: true
      when: not ci|bool

    - name: add user to the libvirt/container groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: libvirt
      become: true
      when: not ci|bool

    - name: setup qemu group in /etc/libvirt/qemu.conf
      lineinfile:
        path: /etc/libvirt/qemu.conf
        regexp: 'group = '
        line: 'group = "kvm"'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: setup libvirt group in /etc/libvirt/libvirtd.conf
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: 'unix_sock_group'
        line: 'unix_sock_group = "libvirt"'
        owner: root
        group: root
        mode: 0644
      become: true

    - name: undefine libvirt guest network
      virt_net: name=default state=absent
      become: true
      when: not ci|bool

    - name: define libvirt guest network
      virt_net:
        name: default
        state: present
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/networks/default.xml.j2') }}"
      become: true
      when: not ci|bool

    - name: undefine libvirt guest
      virt:
        name: "{{ item.type }}{{ item.id }}"
        command: undefine
      with_items: "{{ guests }}"
      become: true
      ignore_errors: true
      when: not ci|bool

    - name: define libvirt guest
      virt:
        command: define
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/{{ item.type }}.xml.j2') }}"
      with_items: "{{ guests }}"
      become: true
      when: not ci|bool

    - name: restart systemd/libvirt services
      systemd: name={{ item }} enabled=true state=restarted
      with_items:
        - systemd-networkd
        - libvirtd
        - virtlogd
      become: true
      when: not ci|bool

    - name: create git and src directories for having fun
      file: path={{ lookup('env', 'HOME') }}/{{ item }} state=directory mode=0700
      with_items:
        - git
        - src

    - name: setup OvS build environment
      pacman:
        state: present
        update_cache: false
        name:
          - gcc
          - make
          - pkgconf
          - autoconf
          - automake
      become: true
      when: latest|bool

    - name: install the latest Open vSwitch
      import_tasks: tasks/openvswitch.yaml
      when: latest|bool
