---
- name: arch-on-air post-installation playbook
  hosts: arch
  vars:
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present force=true update_cache=true
      with_items:
        - vim
        - git
        - tmux
        - mutt
        - tree
        - cscope
        - irssi
        - elinks
        - acpi
        - dialog
        - aspell
        - aspell-en
        - picocom
        - moreutils
        - dosfstools
        - pulseaudio
        - pulseaudio-alsa
        - alsa-utils
      become: true

    - name: install network tools
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - wget
        - curl
        - nmap
        - tcpdump
        - ethtool
        - traceroute
        - net-tools
        - bind-tools
        - conntrack-tools
        - gnu-netcat
        - mtr
        - rsync
        - ebtables
        - dnsmasq
        - openconnect
        - wpa_supplicant
        - ipcalc
      become: true

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=present force=true update_cache=true
      with_items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - xcb-util-image
        - xcb-util-keysyms
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - mupdf
        - chromium
        - qt5-svg
        - qt5-webengine
        - qt5-quickcontrols2
      become: true

    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - linux-headers
        - yasm
        - binutils
        - bc
        - bison
        - flex
        - gcc
        - gdb
        - go
        - m4
        - make
        - autoconf
        - automake
        - libtool
        - pkg-config
        - numactl
        - fakeroot
        - unzip
        - jq
      become: true

    - name: uucp group for picocom
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: uucp
      become: true
      when: not travis_ci|bool

    - name: enable basic systemd services
      systemd: name={{ item }} enabled=true
      with_items:
        - systemd-networkd
        - systemd-resolved
      become: true
      when: not travis_ci|bool

    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - vconsole.conf
        - systemd/network/wlp3s0.network
        - X11/xorg.conf.d/
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: let's suckless!
      import_tasks: tasks/suckless.yml

    - name: we need sounds!
      import_tasks: tasks/audio.yml
