---
- name: arch-on-air post-installation playbook
  hosts: host
  vars:
    travis_ci: false
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - vim
        - tmux
        - tree
        - jq
        - acpi
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - cowsay
        - pulseaudio
        - alsa-utils
      become: true

    - name: install network tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - w3m
        - curl
        - tcpdump
        - traceroute
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - rsync
        - irssi
        - mutt
        - ebtables
        - dnsmasq
      become: true

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - chromium
      become: true

    - name: configure the audio
      import_tasks: tasks/audio.yml
