---
- name: arch-on-air post-installation playbook
  hosts: host
  vars:
    travis_ci: false
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - busybox
        - dosfstools
        - tmux
        - vim
        - tree
        - jq
        - pulseaudio
        - alsa-utils
        - aspell
        - aspell-en
      become: true

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - chromium
      become: true

    - name: install network apps
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - curl
        - tcpdump
        - net-tools
        - bind-tools
        - gnu-netcat
        - traceroute
        - mtr
        - rsync
        - irssi
        - mutt
        - w3m
        - qemu-headless
        - libvirt
        - libvirt-python2
        - ebtables
        - dnsmasq
      become: true

    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - bc
        - gcc
        - gcc-fortran
        - git
        - make
        - cscope
        - autoconf
        - automake
        - libtool
        - pkg-config
        - unzip
        - go
        - docker
        - docker-machine
        - python2
        - python2-pip
        - jre8-openjdk-headless
      become: true

    - name: configure the audio
      import_tasks: tasks/audio.yml
