---
- name: arch-on-air post-installation play
  hosts: host
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "/usr/local/git/"
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present update_cache=true
      items:
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - tmux
        - vim
        - irssi
        - mutt
        - w3m
        - tree
        - jq
      become: true

    - name: install developer tools
      pacman: name={{ item }} state=present update_cache=false
      items:
        - bc
        - git
        - gcc
        - gcc-fortran
        - make
        - cscope
        - autoconf
        - automake
        - libtool
        - pkg-config
        - unzip
        - go
        - docker
        - python2
        - python2-pip
        - jre8-openjdk-headless
      become: true

    - name: install network related tools
      pacman: name={{ item }} state=present update_cache=false
      items:
        - curl
        - tcpdump
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - traceroute
      become: true

    - name: install audio related packages as in README.md
      pacman: name={{ item }} state=present update_cache=false
      items:
        - pulseaudio
        - alsa-utils
      become: true

    - name: configure the audio
      import_tasks: tasks/audio.yml

    - name: install graphical tools
      pacman: name={{ item }} state=present update_cache=true
      items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - chromium
      become: true

    - name: configure kvm/libvirt environment
      pacman: name={{ item }} state=installed
      items:
        - qemu-headless
        - libvirt
        - libvirt-python2
        - ebtables
        - dnsmasq
      become: true

    - name: configure the docker environment
      import_tasks: tasks/docker.yml
      when: not travis_ci|bool

    - name: add user to the developer groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: git,docker
      become: true
      when: not travis_ci|bool

    - name: create git root directory
      file: path={{ gitpath }} state=directory group=git mode=0770
      become: true

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yml
      when: latest|bool and not travis_ci|bool

    - name: install the latest golang
      import_tasks: tasks/golang.yml
      vars:
        bootstrap: /usr/lib/go

    - name: install the latest etcd
      import_tasks: tasks/etcd.yml
      when: latest|bool

    - name: install the latest terraform
      import_tasks: tasks/terraform.yml
      when: latest|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: latest|bool
