---
- name: arch-on-air post-installation playbook
  hosts: arch
  vars:
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
  gather_facts: false
  tasks:
    - name: install console apps
      pacman:
        name:
          - vim
          - git
          - tmux
          - mutt
          - tree
          - cscope
          - irssi
          - elinks
          - acpi
          - dialog
          - aspell
          - aspell-en
          - picocom
          - moreutils
          - dosfstools
          - pulseaudio
          - pulseaudio-alsa
          - alsa-utils
        state: present
        force: true
        update_cache: true
      become: true

    - name: install network tools
      pacman:
        name:
          - wget
          - curl
          - nmap
          - tcpdump
          - ethtool
          - traceroute
          - net-tools
          - bind-tools
          - conntrack-tools
          - gnu-netcat
          - mtr
          - rsync
          - ebtables
          - dnsmasq
          - openconnect
          - wpa_supplicant
          - ipcalc
          - avahi
          - nss-mdns
          - wireshark-cli
        state: present
        force: true
        update_cache: false
      become: true

    - name: install graphical libraries & tools
      pacman:
        name:
          - gcr
          - libxft
          - libxinerama
          - xf86-video-intel
          - xf86-input-libinput
          - xf86-input-synaptics
          - xorg-server
          - xorg-xinit
          - xorg-xset
          - xorg-xsetroot
          - xorg-xinput
          - xorg-xprop
          - xcb-util-image
          - xcb-util-keysyms
          - ttf-freefont
          - gtk3
          - webkit2gtk
          - mupdf
          - chromium
          - imagemagick
          - qt5-svg
          - qt5-webengine
          - qt5-quickcontrols2
        state: present
        force: true
        update_cache: true
      become: true

    - name: add user to uucp for picocom and wireshark for tshark
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: uucp,wireshark
      become: true
      when: not travis_ci|bool

    - name: capabilities for wireshark
      capabilities:
        path: /usr/bin/dumpcap
        capability: "{{ item }}"
        state: present
      with_items:
        - cap_net_raw+eip
        - cap_net_admin+eip
      become: true

    - name: enable basic systemd services
      systemd: name={{ item }} enabled=true
      with_items:
        - systemd-networkd
        - systemd-resolved
        - avahi-daemon
      become: true
      when: not travis_ci|bool

    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - vconsole.conf
        - systemd/network/wlp3s0.network
        - X11/xorg.conf.d/
      become: true

    - name: Enable mDNS/DNS-SD in /etc/nsswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'
      become: true

    - name: install minimum developer tools for suckless and more!
      pacman: name={{ item }} state=present force=true update_cache=false
      with_items:
        - gcc
        - make
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: let's suckless!
      import_tasks: tasks/suckless.yml

    - name: we need sounds!
      import_tasks: tasks/audio.yml
