---
- name: setup post-installation provisioning
  hosts: host
  vars:
    verbose: true
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present update_cache=true
      items:
        - tmux
        - vim
        - irssi
        - mutt
        - w3m
        - cscope
        - tcpdump
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - traceroute
      become: true
      register: result

    - name: print the result
      debug: var=result
      delegate_to: localhost
      when: verbose|bool
