---
- name: arch-on-air post-installation playbook
  hosts: arch
  vars:
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
  gather_facts: false
  tasks:
    - name: install console apps
      pacman:
        state: present
        force: true
        update_cache: true
        name:
          - vim
          - git
          - tmux
          - mutt
          - tree
          - cscope
          - irssi
          - elinks
          - acpi
          - dialog
          - aspell
          - aspell-en
          - picocom
          - moreutils
          - dosfstools
          - exfat-utils
          - pulseaudio
          - pulseaudio-alsa
          - alsa-utils
          - rng-tools
          - haveged
      become: true

    - name: install network tools
      pacman:
        state: present
        force: true
        update_cache: false
        name:
          - wget
          - curl
          - nmap
          - tcpdump
          - ethtool
          - traceroute
          - net-tools
          - bind-tools
          - conntrack-tools
          - gnu-netcat
          - mtr
          - rsync
          - ebtables
          - dnsmasq
          - openconnect
          - wpa_supplicant
          - ipcalc
          - avahi
          - nss-mdns
          - wireshark-cli
      become: true

    - name: add user to uucp for picocom and wireshark for tshark
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: uucp,wireshark
      become: true
      when: not travis_ci|bool

    - name: capabilities for wireshark
      capabilities:
        path: /usr/bin/dumpcap
        capability: "{{ item }}"
        state: present
      with_items:
        - cap_net_raw+eip
        - cap_net_admin+eip
      become: true

    - name: enable basic systemd services
      systemd: name={{ item }} enabled=true
      with_items:
        - systemd-networkd
        - systemd-resolved
        - avahi-daemon
      become: true
      when: not travis_ci|bool

    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - vconsole.conf
        - systemd/network/wlp3s0.network
      become: true

    - name: Enable mDNS/DNS-SD in /etc/nsswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'
      become: true

    - name: install minimum developer tools for suckless and more!
      pacman:
        state: present
        force: true
        update_cache: false
        name:
          - gcc
          - make
          - pkgconf
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: we need sounds!
      import_tasks: tasks/audio.yml
