---
- name: setup post-installation provisioning
  hosts: host
  vars:
    latest: true
    verbose: true
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present update_cache=true
      items:
        - tmux
        - vim
        - irssi
        - mutt
        - w3m
      become: true
      register: result

    - name: print the result
      debug: var=result
      delegate_to: localhost
      when: verbose|bool

    - name: install compilers
      pacman: name={{ item }} state=present update_cache=false
      items:
        - go
        - cscope
      become: true
      register: result

    - name: print the result
      debug: var=result
      delegate_to: localhost
      when: verbose|bool

    - name: install network related tools
      pacman: name={{ item }} state=present update_cache=false
      items:
        - tcpdump
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - traceroute
      become: true
      register: result

    - name: print the result
      debug: var=result
      delegate_to: localhost
      when: verbose|bool

    - name: install pre-requisite packages for ansible
      pacman: name={{ item }} state=present update_cache=false
      items:
        - python2
        - python2-pip
      become: true
      register: result

    - name: print the result
      debug: var=result
      delegate_to: localhost
      when: verbose|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: latest|bool
