---
- name: install post-installation apps
  hosts: host
  vars:
    latest: false
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "/usr/local/git/"
  gather_facts: false
  tasks:
    - name: install console apps
      pacman: name={{ item }} state=present update_cache=true
      items:
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - tmux
        - vim
        - irssi
        - mutt
        - w3m
      become: true
      register: result

    - name: install compilers & developer tools
      pacman: name={{ item }} state=present update_cache=false
      items:
        - go
        - make
        - autoconf
        - automake
        - libtool
        - unzip
        - cscope
      become: true
      register: result

    - name: install network related tools
      pacman: name={{ item }} state=present update_cache=false
      items:
        - curl
        - tcpdump
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - traceroute
      become: true
      register: result

    - name: create git root directory
      file:
        path: "{{ gitpath }}"
        state: directory
        group: git
        mode: 0775
      become: true

    - name: install audio related packages as in README.md
      pacman: name={{ item }} state=present update_cache=false
      items:
        - pulseaudio
        - alsa-utils

    - name: configure the audio
      import_tasks: tasks/audio.yml

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yml
      when: latest|bool and not travis_ci|bool

    - name: install the latest golang
      import_tasks: tasks/golang.yml
      vars:
        bootstrap: /usr/lib/go
      when: latest|bool

    - name: install the latest terraform
      import_tasks: tasks/terraform.yml
      when: latest|bool

    - name: install pre-requisite packages for ansible
      pacman: name={{ item }} state=present update_cache=false
      items:
        - python2
        - python2-pip
      become: true
      register: result

    - name: install the latest ansible
      import_tasks: tasks/ansible.yml
      when: latest|bool
