---
- name: clone the ansible git repo
  git:
    repo: git@github.com:ansible/ansible
    dest: /usr/local/git/ansible
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: print the result
  debug: var=git
  delegate_to: localhost
  when: verbose|bool

- name: install python packages for ansible
  pip: requirements=/usr/local/git/ansible/requirements.txt
  become: true
  register: result

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: install the latest ansible
  command: "{{ ansible_python_interpreter }} setup.py install"
  args:
    chdir: /usr/local/git/ansible
  become: true
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool
