---
- name: clone the ansible git repo
  git:
    repo: "{{ gitsite }}ansible/ansible"
    dest: "{{ gitpath }}ansible"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: install python packages for ansible
  pip:
    requirements: "{{ gitpath }}ansible/requirements.txt"
  become: true
  register: result

- name: install the latest ansible
  command: "{{ ansible_python_interpreter }} setup.py install"
  args:
    chdir: "{{ gitpath }}ansible"
  become: true
  register: result
  when: git.before != git.after
