---
- name: install pre-requisite packages for ansible
  apt: name={{ item }} state=present update_cache=no
  items:
    - python
    - python-pip
    - libssl-dev
  become: true

- name: clone the ansible git repo
  git:
    repo: git@github.com:ansible/ansible
    dest: /usr/local/git/ansible
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: result

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: install python packages for ansible
  pip: requirements=/usr/local/git/ansible/requirements.txt
  become: true
  register: result

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: install the latest ansible
  command: python setup.py install
  args:
    chdir: /usr/local/git/ansible
  become: true
  register: result

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool
