---
- name: install packages
  apt: name={{ item }} state=present update_cache=yes
  items:
    - python
    - python-pip
    - libssl-dev
  become: true

- name: clone git repos
  git:
    repo: git@github.com:ansible/ansible
    dest: /usr/local/git/ansible
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: result

- name: print the result
  debug: var=result
  when: verbose|bool

- name: install python packages for ansible
  pip: requirements=/usr/local/git/ansible/requirements.txt
  become: true
  register: result

- name: print the result
  debug: var=result
  when: verbose|bool

- name: install the latest ansible
  command: python setup.py install
  args:
    chdir: /usr/local/git/ansible
  become: true
  register: result

- name: print the result
  debug: var=result
  when: verbose|bool
