---
- name: add user to the docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    append: true
    groups: docker
  become: true

- name: start the docker daemon
  service: name=docker enabled=true state=started
  become: true

- name: clone the docker-compose git repo
  git:
    repo: "{{ gitsite }}docker/compose"
    dest: "{{ gitpath }}docker-compose"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: install python packages for docker-compose
  pip:
    requirements: "{{ gitpath}}/docker-compose/requirements-dev.txt"
  become: true
  when: git.before != git.after

- name: install the latest docker-compose
  command: "{{ ansible_python_interpreter }} setup.py install"
  args:
    chdir: "{{ gitpath }}docker-compose"
  become: true
  when: git.before != git.after
