---
- name: clone the golang git repo
  git:
    repo: "{{ gitsite }}golang/go"
    dest: "{{ gitpath }}go"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: print the result
  debug: var=git
  delegate_to: localhost
  when: verbose|bool

- name: build & install the latest golang
  shell: GOROOT_BOOTSTRAP={{ bootstrap }} ./make.bash
  args:
    chdir: /usr/local/git/go/src
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool
