---
- name: get the latest kubernetes
  command: go get -u {{ item }}
  items:
    - k8s.io/kubernetes/cmd/kubectl
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"

- name: build & install the latest kubernetes
  make:
    chdir: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
