---
- name: git clone the latest OvS from github.com
  git:
    repo: "{{ gitsite }}openvswitch/ovs"
    dest: "{{ gitpath }}ovs"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: build OvS, as in ovs/Documentaions/intro/install/debian.rst
  shell: >
    cd "{{ gitpath }}ovs" &&
    DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules binary

- name: download the OvS/OVN deb packages
  fetch: src=/tmp/{{ item }} dest=/tmp/{{ ansible_user_id }}/{{ item }} flat=yes
  with_items:
    - openvswitch-datapath-dkms_{{ ovs_version }}_all.deb
    - openvswitch-common_{{ ovs_version }}_amd64.deb
    - openvswitch-switch_{{ ovs_version }}_amd64.deb
    - ovn-common_{{ ovs_version }}_amd64.deb
    - ovn-central_{{ ovs_version }}_amd64.deb
    - ovn-host_{{ ovs_version }}_amd64.deb
