---
- name: git clone the latest OvS from github.com
  git:
    repo: "{{ gitsite }}openvswitch/ovs"
    dest: "{{ gitpath }}ovs"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: bootstrap OvS build environment
  command: ./boot.sh
  args:
    chdir: "{{ gitpath }}ovs"
  when: git.before != git.after

- name: configure OvS with ./configure
  command: ./configure
  args:
    chdir: "{{ gitpath }}ovs"
  when: git.before != git.after

- name: build OvS!
  make:
    chdir: "{{ gitpath }}ovs"
  when: git.before != git.after

- name: install OvS executables
  make:
    chdir: "{{ gitpath }}ovs"
    target: install
  become: true
  when: git.before != git.after
