---
- name: clone the protobuf git repo
  git:
    repo: "{{ gitsite }}google/protobuf"
    dest: "{{ gitpath }}protobuf"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: print the result
  debug: var=git
  delegate_to: localhost
  when: verbose|bool

- name: create ./configure script through autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ gitpath }}protobuf"
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: configure the protobuf
  command: ./configure chdir="{{ gitpath }}protobuf"
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: build protobuf runtime and protoc protobuf compiler
  make:
    chdir: "{{ gitpath }}protobuf"
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: install the protobuf runtime and compiler
  make:
    chdir: "{{ gitpath }}protobuf"
    target: install
  become: true
  register: result
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: refresh the shared library cache
  command: ldconfig
  register: result
  become: true
  when: git.before != git.after

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool

- name: check the protobuf version
  command: protoc --version
  environment:
    PATH: "{{ lookup('env', 'PATH') }}"
  changed_when: false
  register: result

- name: print the result
  debug: var=result
  delegate_to: localhost
  when: verbose|bool
