---
- name: install python standard packages
  pip:
    name:
      - python-dotenv
      - scapy
      - docker
      - docker-compose
      - cloudsmith-cli
      - py-mysql
      - csvkit
  become: true
