---
- name: install RabbitMQ packages
  apt: name={{ item }} state=present update_cache=false
  items:
    - rabbitmq-server
  become: true
  register: result

- name: print out the result
  debug: var=result
  when: verbose|bool

- name: start required services
  service: name={{ item }} state=started
  items:
    - rabbitmq-server
  register: result

- name: print out the result
  debug: var=result
  when: verbose|bool
