---
- name: install RabbitMQ packages
  apt: name={{ item }} state=present update_cache=false
  items:
    - rabbitmq-server
  become: true
  register: result

- name: print out the result
  debug: var=result
  when: verbose|bool

- name: create RabbitMQ required directories
  file: path={{ item }} state=directory owner=rabbitmq group=rabbitmq mode=0755
  items:
    - /var/log/rabbitmq
    - /var/lib/rabbitmq/mnesia/rabbit

- name: start required services
  service: name={{ item }} state=started
  items:
    - rabbitmq-server
  register: result

- name: print out the result
  debug: var=result
  when: verbose|bool
