---
- name: git clone the latest tendermint from github.com
  git:
    repo: "{{ gitsite }}tendermint/tendermint"
    dest: "{{ gitpath }}tendermint"
    update: yes
    force: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: download the required go tools/packages
  make:
    chdir: "{{ gitpath }}tendermint"
    target: tools
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
  when: git.before != git.after

- name: build tendermint!
  make:
    chdir: "{{ gitpath }}tendermint"
    target: install
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
  when: git.before != git.after
