---
version: 2
default: &defaults
  working_directory: /home/circleci/project/arch-on-air
  docker:
    - image: archlinux/base:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci/project/arch-on-air
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to run the test
          command: pacman -Sy --noconfirm tar gcc make grep git python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= make test
