---
version: 2
default: &defaults
  working_directory: /home/circleci/project/arch-on-air
  docker:
    - image: archlinux/base:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - ansible:
          requires:
            - checkout
      - provision:
          requires:
            - checkout
      - all:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install tar to build the workspace
          command: pacman -Sy --noconfirm tar
      - persist_to_workspace:
          root: /home/circleci/project/arch-on-air
          paths:
            - .
  ansible:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to build the latest ansible
          command: pacman -Sy --noconfirm tar make git python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= make ansible
  provision:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to run the test
          command: pacman -Sy --noconfirm tar gcc make grep git python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= CI=true GITURL=https://github.com/ make ansible provision
  all:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to run the test
          command: pacman -Sy --noconfirm tar gcc make grep git python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= CI=true GITURL=https://github.com/ make all
