---
- name: setup ubuntu guests
  hosts: guests
  vars:
    verbose: false
  gather_facts: false
  tasks:
    - name: install packages
      apt: name={{ item }} state=present update_cache=yes
      items:
        - golang-1.6
        - w3m
      become: true

    - name: add user to the src group
      user:
        name: "{{ ansible_user }}"
        group: adm
        groups: src,sudo
        append: yes
      become: true

    - name: create /usr/local/git directory
      file: path=/usr/local/git state=directory group=src mode=0775
      become: true

    - name: clone golang repo
      git:
        repo: git@github.com:golang/go
        dest: /usr/local/git/go
        update: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      register: result

    - name: print the result
      debug: var=result
      when: verbose|bool

    - name: compile the latest golang
      shell: GOROOT_BOOTSTRAP=/usr/lib/go-1.6 ./make.bash
      args:
        chdir: /usr/local/git/go/src
      register: result

    - name: print the result
      debug: var=result
      when: verbose|bool
